### ISSUE TITLE
Node config doesn't change according to `CKB_NETWORK`

### ISSUE THREAD

**Issue by keroro520** [linkdesu/ckb-env#1]
The [hosting ckb.toml](https://github.com/linkdesu/ckb-env/blob/c815a6a0d8fce17c8f66a6e1563ae5d07cc69add/ckb-node/ckb.toml) is for CKB mainnet, changing the environment variable `CKB_NETWORK` seems doesn't work for it.

And I am not sure that whether `CKB_NETWORK` indicates to [`CKB_CHAIN`](https://hub.docker.com/layers/nervos/ckb/latest/images/sha256-26fd6408c03579cf84108e3880272e3ac191741a7732fcbda759849c39dbe6a9?context=explore)?

**Comment by linkdesu** [comment]
The `CKB_NETWORK` is `CKB_CHAIN`. But it can not works very well, it only changes the env of the ckb-node service in compose.yaml. The config files of each service still need to be modified manually base on your requirement.

If you have any good idea to solve this problem just let me know, I will try to make it easier to setup a ckb development environment.

And sorry for late. 😂
